refactor: Error handling (#64)
* refactor: catch error in handleApiRequest

* refactor: move handleApiRequest in api folder

* refactor: re-create errors architecture

* refactor: create BusinessError

* refactor: handle BusinessError in handleApiRequest

* fix: HttpErrorDto api doc

* refactor: Move request service to services folder

* feat: handle BusinessError in LockliteApiRequestService

* refactor: Move abstract errors in shared module

* refactor: Use HttpError & BusinessError in frontend

* refactor: Add toString methods in errors

* fix: toString methods in errors

* refactor: LockliteApiRequestService - create handleNoDataCase

* refactor: LockliteApiRequestService - create _errorMessage

* refactor: LockliteApiRequestService - create _parseData & _handleParseError

* fix: LockliteApiRequestService - create _parseData & _handleParseError

* refactor: LockliteApiRequestService - create _handleNoData

* refactor: LockliteApiRequestService - rename methods

* refactor: Request services - move errorMessage in abstract

* refactor: Request services - create _handleResponseNotOk

* fix: Request services - create _handleResponseNotOk

* fix: Request services - rename _fetch to _request

* fix: Request services - create _fetch

* fix: Request services - protected naming

* refactor: move VaultAlreadyExistsError in vaults folder

* feat: create VaultLabelTooLongError

* fix: create BusinessErrorCodeEnumDto.VAULT_LABEL_TOO_LONG

* fix: add VaultAlreadyExistsError in api doc

* fix: tests of handleApiRequest

* refactor: move http error test

* refactor: move handle-api-request.test.ts in api folder

* fix: move request.service.test.ts in services folder

* fix: Type error: Variable 'vaultCreated' is used before being assigned.

* fix: use uri instead of url

* fix: typo

* fix: Property 'data' does not exist on type 'HttpResponseDto<Data>'

* chore(linter): add @typescript-eslint/no-use-before-define & @typescript-eslint/no-unnecessary-condition rules